name: docGPT Generate
description: Generates docs for Overmind sources, using doc-gen and chatGPT
author: Overmind
inputs:
  milliseconds:
    required: true
    description: requires changed files in doc-data
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'