name: docGPT Generate
description: Generates docs for Overmind sources, using doc-gen and chatGPT
author: Overmind
inputs:
  milliseconds:
    required: true
    description: requires changed files in doc-data
    default: 'default value if applicable'
runs:
  using: "composite"
  steps:
    - name: Cache Terraform Providers
      id: cache-terraform
      uses: tj-actions/changed-files@v35
      with:
        files: docs-data/**