name: docGPT Generate
description: Generates docs for Overmind sources, using doc-gen and chatGPT
author: Overmind
inputs:
  milliseconds:
    required: true
    description: requires changed files in doc-data
    default: 'default value if applicable'

  NOTION_API_KEY:
    description: "Notion Database API Key"
    required: true

  OPENAI_KEY:
    description: "OpenAI API key"
    required: true

  TYPES_DATABASE_ID:
    description: "Notion Types Database ID"
    required: true

  LINKS_DATABASE_ID:
    description: "Notion Links Database ID"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Check changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
        files: docs-data/**
    - uses: actions/setup-node@v3
      with: 
        node-version: ${{ env.NODE_VERSION }}
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      run: |
          npm install
          npm run typecheck

    - name: Run step if any file(s) in the docs folder change
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: |
          echo "One or more files in the docs folder has changed."
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}*; do npx ts-node src/createPage.ts < $file; done 
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}*; do npx ts-node src/linksPage.ts < $file; done
      env:
          NOTION_API_KEY: ${{ inputs.NOTION_API_KEY }}
          OPENAI_KEY: ${{ inputs.OPENAI_KEY }}
          TYPES_DATABASE_ID: ${{ inputs.TYPES_DATABASE_ID }}
          LINKS_DATABASE_ID: ${{ inputs.LINKS_DATABASE_ID }}
      shell: bash